# Generated by Django 4.2.24 on 2025-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ipfs_hash', models.CharField(max_length=60, unique=True)),
                ('issue_date', models.DateField()),
            ],
        ),
    ]
